# Generated by Django 4.1.7 on 2023-04-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eqms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="obselescencedata",
            name="serial_number",
            field=models.CharField(default=232, max_length=255),
            preserve_default=False,
        ),
    ]
